# Site wide configuration

title: self·edge
description: "Selfedge Publishing"
#teaser: lino.jpg
locale: en_GB
url: http://hackbox.local/~wim/selfedge


# Jekyll configuration
# For plugins
safe: true
sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
markdown: kramdown
#kramdown:
#  toc_levels: 1..2
highlighter: none
#highlighter: rouge
#highlighter: pygments
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed


# Site owner
owner:
  name: Wim 
  web: http://www.selfedge.org.uk
  bio: ""
#  avatar: W_160px.jpg # 160x160 px image for author byline

#include:
#  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec

